- name: this playbook installs nginx 
  hosts: all
  vars:
    - greeting_msg: Devops
    - provisioner_tool: Docker
    - cm_tool: Ansible
  tasks:
    - name: testing ping
      ping:
#    - name: install pre-requisite- epel release
#      yum: name=epel-release
#    - name: fix epel repo
#      shell: sed -i "s/mirrorlist=https/mirrorlist=http/" /etc/yum.repos.d/epel.repo
#    - name: install nginx
#      yum: name=nginx state=latest
    - name: create updated nginx web root folder
      file: path=/usr/share/html state=directory mode=0777
    - name: configure the nginx web root folder
      copy: src=default.conf dest=/etc/nginx/conf.d/default.conf
    - name: Startng of  nginx
      service: name=nginx state=restarted
    - name: deploy our customized html page
      template: src=index.html.j2 dest=/usr/share/html/index.html
